subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_30a5d3d0_78e3_46e1_978c_33ca6d62a4e4','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Service').
subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_43bde57d_94bf_423a_9a9b_6c04c1c2041c','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Asset').
subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_55355d8f_0d28_4f47_9d7d_b6f8ab3c5151','http://www.co-ode.org/ontologies/ont.owl#OWLClass_30a5d3d0_78e3_46e1_978c_33ca6d62a4e4').
subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_57d41068_4181_4bc6_81f4_72d40db51fa3','http://www.co-ode.org/ontologies/ont.owl#OWLClass_e6c9f1cf_4283_48cd_817a_f5c3752bb0ae').
subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_5fd25d5a_07af_40fa_8388_3a8bd4d70970','http://www.co-ode.org/ontologies/ont.owl#OWLClass_30a5d3d0_78e3_46e1_978c_33ca6d62a4e4').
subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_6ba1eff7_1df2_452e_9ac6_999af0bc35a1','http://www.co-ode.org/ontologies/ont.owl#OWLClass_e6c9f1cf_4283_48cd_817a_f5c3752bb0ae').
subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_8f807b2b_8eb9_4346_9134_95314240ee1e','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Service').
subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_bbfa996c_3edd_4945_9a9b_396345fd4e3f','http://www.co-ode.org/ontologies/ont.owl#OWLClass_30a5d3d0_78e3_46e1_978c_33ca6d62a4e4').
subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_c629a900_0010_4a12_bf53_fcedc7b38bea','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Asset').
subClassOf('http://www.co-ode.org/ontologies/ont.owl#OWLClass_e6c9f1cf_4283_48cd_817a_f5c3752bb0ae','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Service').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Abuse','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AnomalyBasedAbuse','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Abuse').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/DataAnnihilation','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/IaaSLevelProbe','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Probe').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/IllegalAccess','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/InformationLeakage','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/KnowledgeBasedAbuse','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Abuse').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Misuse','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/PaaSLevelProbe','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Probe').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/SaaSLevelProbe','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Probe').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Service','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Asset').
subClassOf('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Suspicious','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
propertyDomain('http://www.co-ode.org/ontologies/ont.owl#OWLObjectProperty_16fddbd3_833b_4962_b0c3_f634d5329cc9','http://www.co-ode.org/ontologies/ont.owl#OWLClass_30a5d3d0_78e3_46e1_978c_33ca6d62a4e4').
propertyDomain('http://www.co-ode.org/ontologies/ont.owl#OWLObjectProperty_16fddbd3_833b_4962_b0c3_f634d5329cc9','http://www.co-ode.org/ontologies/ont.owl#OWLClass_8f807b2b_8eb9_4346_9134_95314240ee1e').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#OSMadeOf','http://www.co-ode.org/ontologies/ont.owl#OWLClass_bbfa996c_3edd_4945_9a9b_396345fd4e3f').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#VMMadeOf','http://www.co-ode.org/ontologies/ont.owl#OWLClass_55355d8f_0d28_4f47_9d7d_b6f8ab3c5151').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#canLeadTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Weakness').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#directedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackScenario').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#hasVulneraiblity','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Asset').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#hasWeakness','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Asset').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#isAssociated','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Risk').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#isDirectedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#isPartOfConfiguration','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Asset').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#materializesIn','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackScenario').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#menaces','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#provides','http://www.co-ode.org/ontologies/ont.owl#OWLClass_c629a900_0010_4a12_bf53_fcedc7b38bea').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#totalRiskAssociatedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#TotalRisk').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#useService','http://www.co-ode.org/ontologies/ont.owl#OWLClass_43bde57d_94bf_423a_9a9b_6c04c1c2041c').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#useVulnerability','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Exploit').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#uses','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/ThreatAgent').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesProbabiityFunction','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesSaaS','http://www.co-ode.org/ontologies/ont.owl#OWLClass_30a5d3d0_78e3_46e1_978c_33ca6d62a4e4').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesSaaS','http://www.co-ode.org/ontologies/ont.owl#OWLClass_8f807b2b_8eb9_4346_9134_95314240ee1e').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesSaaS','http://www.co-ode.org/ontologies/ont.owl#OWLClass_e6c9f1cf_4283_48cd_817a_f5c3752bb0ae').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#utilizes','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/affected','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/appliedOn','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Precondition').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/appliedOnEffect','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Postcondition').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasDeadline','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackScenario').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasDescription','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasEffect','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasEffectThreshold','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasEffected','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasIntensityValue','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasMethod','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Probe').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPostCondition','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackScenario').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPostPredicate','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Postcondition').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPrePredicate','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Precondition').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPrecondition','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackScenario').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasThreshold','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasTrustworthiness','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackIndicator').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/indicates','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackIndicator').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isAssociatedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackIndicator').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isCausedBy','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isCausedByOrigin','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isDetectedIn','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isDirectedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isEvaluatedBy','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isMonitoredBy','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isVerifiedIn','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Precondition').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/precedes','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#AuthRequired','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#CVE_ID','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#CVSS_Score','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Complexity','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Date','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Exploit').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Description','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Weakness').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#EaseOfDiscovery','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#EaseOfExploit','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ID','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Exploit').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ID','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#MethodUsed','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Probe').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Name','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Weakness').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Name','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Platform','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Exploit').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ProbeName','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Probe').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Scope','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Weakness').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Source','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ThreatName','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Type','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Exploit').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Type','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
propertyDomain('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#hasRisk','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyRange('http://www.co-ode.org/ontologies/ont.owl#OWLObjectProperty_16fddbd3_833b_4962_b0c3_f634d5329cc9','http://www.co-ode.org/ontologies/ont.owl#OWLClass_e6c9f1cf_4283_48cd_817a_f5c3752bb0ae').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#OSMadeOf','http://www.co-ode.org/ontologies/ont.owl#OWLClass_9b6a4789_6444_4a7d_94c8_8258672cee5c').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#OSMadeOf','http://www.co-ode.org/ontologies/ont.owl#OWLClass_fb3a2355_82a0_416b_9383_c31d7e618a3e').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#VMMadeOf','http://www.co-ode.org/ontologies/ont.owl#OWLClass_5d0dea09_667e_426b_b54c_e951d94778ce').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#VMMadeOf','http://www.co-ode.org/ontologies/ont.owl#OWLClass_6e80ba05_ed04_4453_9364_ec8ac91ac834').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#VMMadeOf','http://www.co-ode.org/ontologies/ont.owl#OWLClass_cd79b9e1_249a_4931_bdb7_70ef36c439e2').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#canLeadTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#directedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#System').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#hasVulneraiblity','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#hasWeakness','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Weakness').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#isAssociated','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#isDirectedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Asset').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#isPartOfConfiguration','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Configuration').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#materializesIn','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#menaces','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#System').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#provides','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Service').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#totalRiskAssociatedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#System').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#useService','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Service').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#useVulnerability','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#uses','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesProbabiityFunction','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/ProbabilityFunction').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesSaaS','http://www.co-ode.org/ontologies/ont.owl#OWLClass_e6c9f1cf_4283_48cd_817a_f5c3752bb0ae').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#utilizes','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Exploit').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/affected','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Asset').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/appliedOn','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/appliedOnEffect','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasDeadline','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Deadline').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasDescription','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Description').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasEffect','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasEffectThreshold','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/EffectThreshold').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasEffected','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/SecurityObjective').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasIntensityValue','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/IntensityScore').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasMethod','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/MonitoringMethod').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPostCondition','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Postcondition').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPostPredicate','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/PostPredicate').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPrePredicate','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/PrePredicate').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPrecondition','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Precondition').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasThreshold','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/ConfidenceThreshold').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasTrustworthiness','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Trustworthiness').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/indicates','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isAssociatedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Probe').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isCausedBy','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/ThreatAgent').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isCausedByOrigin','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Origin').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isDetectedIn','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Timestamp').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isDirectedTo','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Destination').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isEvaluatedBy','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackIndicator').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isMonitoredBy','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Probe').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isVerifiedIn','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Time').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/precedes','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#AuthRequired','http://www.w3.org/2001/XMLSchema#boolean').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#CVE_ID','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#CVSS_Score','http://www.w3.org/2001/XMLSchema#unsignedInt').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Complexity','http://www.w3.org/2001/XMLSchema#unsignedInt').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Date','http://www.w3.org/2001/XMLSchema#dateTime').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Description','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#EaseOfDiscovery','http://www.w3.org/2001/XMLSchema#unsignedInt').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#EaseOfExploit','http://www.w3.org/2001/XMLSchema#unsignedInt').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ID','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#MethodUsed','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Name','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Platform','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ProbeName','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Scope','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Source','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ThreatName','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Type','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#hasRisk','http://www.w3.org/2001/XMLSchema#unsignedInt').
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLObjectProperty_16fddbd3_833b_4962_b0c3_f634d5329cc9',literal(lang(en,hosts))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#OSMadeOf',literal(lang(en,madeOf))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#VMMadeOf',literal(lang(en,madeOf))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#provides',literal(lang(en,provides))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#useService',uses).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesProbabiityFunction',uses).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesSaaS',literal(lang(en,uses))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/affected',affected).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#MethodUsed',literal(lang(en,'MethodUsed'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ProbeName',literal(lang(en,'Name'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ThreatName',literal(lang(en,'Name'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_30a5d3d0_78e3_46e1_978c_33ca6d62a4e4',literal(lang(en,'IaaS'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_43bde57d_94bf_423a_9a9b_6c04c1c2041c',literal(lang(en,'CloudApplication'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_55355d8f_0d28_4f47_9d7d_b6f8ab3c5151',literal(lang(en,'VirtualMachine'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_57d41068_4181_4bc6_81f4_72d40db51fa3',literal(lang(en,'SoftwareComponent'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_5d0dea09_667e_426b_b54c_e951d94778ce',literal(lang(en,'Memory'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_5fd25d5a_07af_40fa_8388_3a8bd4d70970',literal(lang(en,'Network'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_6ba1eff7_1df2_452e_9ac6_999af0bc35a1',literal(lang(en,'ApplicationData'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_6e80ba05_ed04_4453_9364_ec8ac91ac834',literal(lang(en,'CPU'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_8f807b2b_8eb9_4346_9134_95314240ee1e',literal(lang(en,'PaaS'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_9b6a4789_6444_4a7d_94c8_8258672cee5c',literal(lang(en,'SystemData'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_bbfa996c_3edd_4945_9a9b_396345fd4e3f',literal(lang(en,'OS'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_c629a900_0010_4a12_bf53_fcedc7b38bea',literal(lang(en,'CSP'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_cd79b9e1_249a_4931_bdb7_70ef36c439e2',literal(lang(en,'Storage'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_e6c9f1cf_4283_48cd_817a_f5c3752bb0ae',literal(lang(en,'SaaS'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','http://www.co-ode.org/ontologies/ont.owl#OWLClass_fb3a2355_82a0_416b_9383_c31d7e618a3e',literal(lang(en,'SystemComponet'))).
classAssertion('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#DatabaseAccess').
classAssertion('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#InsicureSSHConnection').
classAssertion('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#PortScan').
classAssertion('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#PortSentryAttackAlert').
classAssertion('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#RemoteCodeExecution').
classAssertion('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#RemoteShell').
classAssertion('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#WebServer400Error').
classAssertion('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#WordpressAdminConsoleAccess').
classAssertion('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack','http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#WordpressScan').
namedIndividual('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#DatabaseAccess').
namedIndividual('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#InsicureSSHConnection').
namedIndividual('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#PortScan').
namedIndividual('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#PortSentryAttackAlert').
namedIndividual('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#RemoteCodeExecution').
namedIndividual('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#RemoteShell').
namedIndividual('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#WebServer400Error').
namedIndividual('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#WordpressAdminConsoleAccess').
namedIndividual('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#WordpressScan').
objectProperty('http://www.co-ode.org/ontologies/ont.owl#OWLObjectProperty_16fddbd3_833b_4962_b0c3_f634d5329cc9').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#OSMadeOf').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#VMMadeOf').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#canLeadTo').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#directedTo').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#hasVulneraiblity').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#hasWeakness').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#isAssociated').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#isDirectedTo').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#isPartOfConfiguration').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#materializesIn').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#menaces').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#provides').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#totalRiskAssociatedTo').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#useService').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#useVulnerability').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#uses').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesProbabiityFunction').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#usesSaaS').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#utilizes').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/affected').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/appliedOn').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/appliedOnEffect').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasDeadline').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasDescription').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasEffect').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasEffectThreshold').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasEffected').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasIntensityValue').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasMethod').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPostCondition').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPostPredicate').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPrePredicate').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasPrecondition').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasThreshold').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/hasTrustworthiness').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/indicates').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isAssociatedTo').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isCausedBy').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isCausedByOrigin').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isDetectedIn').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isDirectedTo').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isEvaluatedBy').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isMonitoredBy').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/isVerifiedIn').
objectProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/precedes').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#AuthRequired').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#CVE_ID').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#CVSS_Score').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Complexity').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Date').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Description').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#EaseOfDiscovery').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#EaseOfExploit').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ID').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#MethodUsed').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Name').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Platform').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ProbeName').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Scope').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Source').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#ThreatName').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Type').
dataProperty('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#hasRisk').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#label').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#comment').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_30a5d3d0_78e3_46e1_978c_33ca6d62a4e4').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_43bde57d_94bf_423a_9a9b_6c04c1c2041c').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_55355d8f_0d28_4f47_9d7d_b6f8ab3c5151').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_57d41068_4181_4bc6_81f4_72d40db51fa3').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_5d0dea09_667e_426b_b54c_e951d94778ce').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_5fd25d5a_07af_40fa_8388_3a8bd4d70970').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_6ba1eff7_1df2_452e_9ac6_999af0bc35a1').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_6e80ba05_ed04_4453_9364_ec8ac91ac834').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_8f807b2b_8eb9_4346_9134_95314240ee1e').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_9b6a4789_6444_4a7d_94c8_8258672cee5c').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_bbfa996c_3edd_4945_9a9b_396345fd4e3f').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_c629a900_0010_4a12_bf53_fcedc7b38bea').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_cd79b9e1_249a_4931_bdb7_70ef36c439e2').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_e6c9f1cf_4283_48cd_817a_f5c3752bb0ae').
class('http://www.co-ode.org/ontologies/ont.owl#OWLClass_fb3a2355_82a0_416b_9383_c31d7e618a3e').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Asset').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Exploit').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Risk').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#System').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Threat').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#TotalRisk').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31#Weakness').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Abuse').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AnomalyBasedAbuse').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Attack').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackIndicator').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/AttackScenario').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/ConfidenceThreshold').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Configuration').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/DataAnnihilation').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Deadline').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Description').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Destination').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Effect').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/EffectThreshold').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/IaaSLevelProbe').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/IllegalAccess').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/InformationLeakage').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/IntensityScore').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/KnowledgeBasedAbuse').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Misuse').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/MonitoringMethod').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Origin').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/PaaSLevelProbe').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/PostPredicate').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Postcondition').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/PrePredicate').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Precondition').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/ProbabilityFunction').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Probe').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/SaaSLevelProbe').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/SecurityObjective').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Service').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Suspicious').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Symptom').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/ThreatAgent').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Time').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Timestamp').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Trustworthiness').
class('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31/Vulnerability').
ontology('http://www.semanticweb.org/valle/ontologies/2019/11/untitled-ontology-31').